services:
  server:
    container_name: web-clipper-server
    image: web-clipper-server
    build:
      context: ..
    network_mode: host
    env_file:
      - ../.env
    volumes:
      - ../uploads:/app/uploads
    restart: unless-stopped
